"""Markdown report generator for SentinelAudit."""

from __future__ import annotations

import logging
from pathlib import Path

from sentinel_audit.core.constants import Severity
from sentinel_audit.core.models import AuditResult
from sentinel_audit.reporting.base import (
    collect_recommendations,
    findings_grouped_by_category,
    top_priority_findings,
)

logger = logging.getLogger(__name__)


class MarkdownReportGenerator:
    """Generate a professional Markdown report."""

    def generate(self, result: AuditResult, output_path: str | None = None) -> str:
        lines: list[str] = []

        lines.append(f"# SentinelAudit Report — {result.label or result.target}")
        lines.append("")
        lines.append("> **Confidential** — This report contains security assessment data.")
        lines.append("")

        # Executive summary
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(f"- **Target:** {result.target}")
        lines.append(f"- **Score:** {result.score.score}/100 ({result.score.grade})")
        lines.append(f"- **Risk:** {result.score.risk_summary}")
        lines.append(f"- **Total findings:** {len(result.findings)}")
        if result.duration_seconds is not None:
            lines.append(f"- **Audit duration:** {result.duration_seconds:.1f}s")
        lines.append("")

        # Top priority actions
        top = top_priority_findings(result)
        if top:
            lines.append("## Top Priority Actions")
            lines.append("")
            for i, f in enumerate(top, 1):
                lines.append(f"{i}. **[{f.severity.value}]** {f.title} — {f.recommendation}")
            lines.append("")

        # System information
        lines.append("## System Information")
        lines.append("")
        si = result.system_info
        lines.append(f"- **Hostname:** {si.hostname}")
        lines.append(f"- **OS:** {si.os_name} {si.os_version}")
        lines.append(f"- **Kernel:** {si.kernel_version}")
        lines.append(f"- **Architecture:** {si.architecture}")
        lines.append(f"- **Uptime:** {si.uptime}")
        lines.append(f"- **CPU:** {si.cpu_model} ({si.cpu_count} cores)")
        lines.append(f"- **Memory:** {si.total_memory_mb} MB")
        ip_addresses = [item.get("address", "") for item in si.network_interfaces if item.get("address")]
        lines.append(f"- **IP addresses:** {', '.join(ip_addresses) if ip_addresses else 'N/A'}")
        lines.append(f"- **Installed packages:** {si.installed_packages_count}")
        lines.append("")

        # Findings by severity
        lines.append("## Findings by Severity")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|---|---:|")
        for severity in Severity:
            lines.append(f"| {severity.value} | {result.score.breakdown.get(severity.value, 0)} |")
        lines.append("")

        # Detailed findings by category
        lines.append("## Detailed Findings")
        lines.append("")
        grouped = findings_grouped_by_category(result)
        if not grouped:
            lines.append("No findings detected.")
            lines.append("")
        else:
            for category, findings in grouped.items():
                lines.append(f"### {category.replace('_', ' ').title()}")
                lines.append("")
                for finding in findings:
                    lines.append(f"#### [{finding.severity.value}] {finding.title} ({finding.id})")
                    lines.append("")
                    lines.append(f"- **Description:** {finding.description}")
                    if finding.evidence:
                        lines.append(f"- **Evidence:** `{finding.evidence}`")
                    if finding.recommendation:
                        lines.append(f"- **Recommendation:** {finding.recommendation}")
                    if finding.reference:
                        lines.append(f"- **Reference:** {finding.reference}")
                    lines.append("")

        # Recommendations
        lines.append("## Recommendations")
        lines.append("")
        recommendations = collect_recommendations(result)
        if recommendations:
            for i, rec in enumerate(recommendations, 1):
                lines.append(f"{i}. {rec}")
        else:
            lines.append("- No specific recommendation.")
        lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by SentinelAudit v1.0.0 — {result.started_at.strftime('%Y-%m-%d %H:%M UTC')}*")
        lines.append("*This report is confidential.*")
        lines.append("")

        markdown = "\n".join(lines)
        if output_path:
            path = Path(output_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(markdown, encoding="utf-8")
            logger.info("Markdown report written to %s", path)

        return markdown
